#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
source "$SCRIPT_DIR/load-ports.sh"

BACKEND_HOST="0.0.0.0"

: "${REDIS_HOST:=127.0.0.1}"
: "${REDIS_SESSION_DB:=0}"
: "${REDIS_PLUGIN_CACHE_DB:=1}"

echo "Starting Compass Hub with:"
echo "  COMPASS_ENV=$COMPASS_ENV"
echo "  PLUGIN_REGISTRY_SOURCE=$PLUGIN_REGISTRY_SOURCE"
echo "  PLUGIN_SERVICES_LOCAL_FILE=$PLUGIN_SERVICES_LOCAL_FILE"
echo "  PLUGIN_REGISTRY_LOCAL_FILE=$PLUGIN_REGISTRY_LOCAL_FILE"
echo "  BACKEND_PORT=$BACKEND_PORT"

podman build --target dev -t compass-refactor-hub:dev "$PROJECT_ROOT/backend"

podman run \
  --rm \
  --name compass-refactor-hub-dev \
  --network host \
  -v "$PROJECT_ROOT:/workspace:Z" \
  -w /workspace \
  -e API_NAME="${API_NAME:-Compass API (Refactor)}" \
  -e COMPASS_ENV="$COMPASS_ENV" \
  -e ENFORCE_ROLE_CHECKS="${ENFORCE_ROLE_CHECKS:-true}" \
  -e DEFAULT_DEV_USER_EMAIL="${DEFAULT_DEV_USER_EMAIL:-dev@local.test}" \
  -e DEFAULT_DEV_ROLES="${DEFAULT_DEV_ROLES:-SuperAdmins}" \
  -e PLUGIN_REGISTRY_SOURCE="$PLUGIN_REGISTRY_SOURCE" \
  -e PLUGIN_SERVICES_LOCAL_FILE="$PLUGIN_SERVICES_LOCAL_FILE" \
  -e PLUGIN_REGISTRY_LOCAL_FILE="$PLUGIN_REGISTRY_LOCAL_FILE" \
  -e FRONTEND_URL="${FRONTEND_URL:-http://localhost:$FRONTEND_PORT}" \
  -e FRONTEND_URL_ALT="${FRONTEND_URL_ALT:-}" \
  -e REDIS_HOST="$REDIS_HOST" \
  -e REDIS_PORT="$REDIS_PORT" \
  -e REDIS_SESSION_DB="$REDIS_SESSION_DB" \
  -e REDIS_PLUGIN_CACHE_DB="$REDIS_PLUGIN_CACHE_DB" \
  -e DATABRICKS_WORKSPACE_URL="${DATABRICKS_WORKSPACE_URL:-}" \
  -e DATABRICKS_HTTP_PATH="${DATABRICKS_HTTP_PATH:-}" \
  -e DATABRICKS_TOKEN="${DATABRICKS_TOKEN:-}" \
  -e DATABRICKS_PLUGINS_TABLE="${DATABRICKS_PLUGINS_TABLE:-}" \
  -e PLUGIN_STREAM_CONNECT_TIMEOUT_SECONDS="${PLUGIN_STREAM_CONNECT_TIMEOUT_SECONDS:-10}" \
  compass-refactor-hub:dev \
  fastapi dev backend/src/main.py --host "$BACKEND_HOST" --port "$BACKEND_PORT"
